# Copyright (c) 2012-2018 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

# scripts that run after cloning repository
install:
  - git submodule update --init googletest
 
image:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013
  
# configurations to add to build matrix
# TODO: VS2010->VS2015 and Win32/Win64 (see https://github.com/google/googletest/blob/master/appveyor.yml)
# TODO: MinGW Makefiles and MSYS Makefiles
configuration:
  - Debug
  - Release
 
# scripts to run before build
before_build:
  - mkdir build
  - cd build
  - cmake -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON -DSQLITECPP_RUN_CPPCHECK=OFF ..

# build examples, and run tests (ie make & make test)
build_script:
  - cmake --build . --config %configuration%
  - ctest --output-on-failure
